from stroke import Stroke

LEFT_CHORDS = {
    'b': Stroke('PW'),
    'd': Stroke('TK'),
    'f': Stroke('TP'),
    'g': Stroke('TKPW'),
    'h': Stroke('H'),
    'k': Stroke('K'),
    'l': Stroke('HR'),
    'm': Stroke('PH'),
    'n': Stroke('TPH'),
    'p': Stroke('P'),
    'r': Stroke('R'),
    's': Stroke('S'),
    't': Stroke('T'),
    'v': Stroke('SR'),
    'w': Stroke('W'),
    'j': Stroke('KWR'),
    'z': Stroke('SWR'),
    'ʃ': Stroke('SH'),
    'θ': Stroke('TH'),
    'ð': Stroke('TH'),
    'ʧ': Stroke('KH'),
    'ʤ': Stroke('SKWR'),
}

MID_CHORDS = {
    'a': Stroke('A'),
    'o': Stroke('AU'),
    'ɔ': Stroke('AU'),
    'ɛ': Stroke('E'),
    'ə': Stroke('U'),
    'ə́': Stroke('U'),
    'ɪ': Stroke('EU'),
    'ɪ́': Stroke('EU'),
    'ɛj': Stroke('AEU'),
    'ɪj': Stroke('AOE'),
    'ɑj': Stroke('AOEU'),
    'əw': Stroke('OE'),
    'ʉw': Stroke('AOU'),
    'aw': Stroke('OU'),
    'oj': Stroke('OEU'),
}

RIGHT_CHORDS = {
    'b': Stroke('-B'),
    'd': Stroke('-D'),
    'f': Stroke('-F'),
    'g': Stroke('-G'),
    'k': Stroke('-BG'),
    'l': Stroke('-L'),
    'm': Stroke('-PL'),
    'n': Stroke('-PB'),
    'p': Stroke('-P'),
    'r': Stroke('-R'),
    's': Stroke('-S'),
    't': Stroke('-T'),
    'v': Stroke('-FB'),
    'z': Stroke('-Z'),
    'ŋ': Stroke('-PBG'),
    'ʃ': Stroke('-GS'),
    'θ': Stroke('-GT'),
    'ð': Stroke('-GT'),
    'ʧ': Stroke('-FP'),
    'ʤ': Stroke('-PBLG'),
}

NON_RIGHT_CHORDS = LEFT_CHORDS | MID_CHORDS
